### ISSUE TITLE
Proposer les données sous forme de data.frame

### ISSUE THREAD

**Issue by oliviermeslin** [pierre-lamarche/DoReMIFaSol#10]
Comme dit dans #8, le problème demeure pour les datasets qui sont fournis avec le _package_.

**Comment by pierre-lamarche** [comment]
Merci @oliviermeslin , résolu [ici](https://github.com/pierre-lamarche/DoReMIFaSol/commit/dd1099988186aaeff44fa0d5f2f7846f6eb73c79)
