### ISSUE TITLE
Bug de la fonction telechargerDonnees sur Mac

### ISSUE THREAD

**Issue by oliviermeslin** [pierre-lamarche/DoReMIFaSol#14]
Je ne parviens pas à utiliser la fonction telechargerDonnees sur mon Mac. Il semble y avoir un bug dans le chemin par défaut:

```
doremifasol::telechargerDonnees("ESTEL_T201", date = "2015")
```
aboutit à cette erreur, dans laquelle il semble qu'il y a un `/` de trop:
```
Erreur : `path` does not exist: ‘/var/folders/wc/0dkp4vf165dfthcsz0ybw3t00000gn/T//RtmpH2UsXf/T201.xls’
```
J'ai ensuite essayé de préciser le dossier:
```
doremifasol::telechargerDonnees("ESTEL_T201", date = "2015", telDir = "/Users/Olivier/Downloads")
```
Et j'obtiens l'erreur:
```
Erreur : `path` does not exist: ‘/Users/Olivier/Downloads/T201.xls’
```

Quelles infos supplémentaires puis-je fournir pour aider au débuggage?

**Comment by pierre-lamarche** [comment]
Le problème est normalement corrigé maintenant. Je t'invite à tester la nouvelle version.

**Comment by pierre-lamarche** [comment]
Bon la construction du chemin a été corrigée, mais ce n'était pas cela le problème ; en réalité, il s'agissait d'une erreur dans le fichier listant les données.

**Comment by oliviermeslin** [comment]
J'ai l'impression que le problème est réglé. Merci!
