### ISSUE TITLE
Ajouter un commentaire dans la fonction telechargerDonnees

### ISSUE THREAD

**Issue by oliviermeslin** [pierre-lamarche/DoReMIFaSol#18]
La fonction `telechargerDonnees` peut télécharger les données soit dans un dossier spécifié par l'argument `teldir`, soit dans un dossier par défaut. Si on se sert de `teldir`, il est facile de savoir où sont les données zip et `xls`, mais dans le cas par défaut, il n'est pas évident de savoir où elles sont.

Je me dis qu'il pourrait être utile que la fonction retourne dans ce un commentaire du genre: `print(paste0("Aucun répertoire d'importation n'est défini. Les données ont été téléchargées par défaut dans le dossier: ", teldir_par_défaut))`.

Est-ce pertinent?

**Comment by pierre-lamarche** [comment]
Oui, je le mets en oeuvre.
