### ISSUE TITLE
Change the package's name / changer le nom du package

### ISSUE THREAD

**Issue by pierre-lamarche** [pierre-lamarche/DoReMIFaSol#6]
`carpenter` est déjà un package R existant.

**Comment by oliviermeslin** [comment]
J'ai pensé à camembR, helicoptR et coleoptR. Ces noms sont tous disponibles, et n'ont aucun sens. Merci de votre attention.

**Comment by pierre-lamarche** [comment]
DoReMIFaSol : Données en R et Mise à disposition par l'Insee FAcilement SOLlicitables ?

**Comment by py-b** [comment]
Salut les gars,
Je suis tombé sur cette page en cherchant des photos de chiens sur Internet.
Est-ce que ce ne serait pas plus digeste entièrement en minuscule ?

**Comment by pierre-lamarche** [comment]
Good point @py-b 
Je vais modifier la dénomination du package dans DESCRIPTION
