### ISSUE TITLE
Proposer les données sous forme de data.trame

### ISSUE THREAD

**Issue by oliviermeslin** [pierre-lamarche/DoReMIFaSol#8]
Je voudrais illustrer dans les fiches `tidyverse` et `data.table` de la doc `UtilitR` comment on convertit un `data.frame` vers un `tibble` ou un `data.table` (avec `as_tibble` et `as.data.table`). Il serait donc préférable que les données du _package_ soient uniquement des `data.frames` de base, et non des `tibble`. Est-ce possible à moindre coût?

**Comment by pierre-lamarche** [comment]
@oliviermeslin tu fais bien de mentionner ce souci, je me disais effectivement qu'il y avait un risque que l'objet produit par la fonction varie de nature selon les paramètres, ce qui serait une propriété non désirable. C'est très facileà corriger, je fais cela de suite et je clos l'_issue_.

**Comment by pierre-lamarche** [comment]
[Done](https://github.com/pierre-lamarche/DoReMIFaSol/commit/6d655ec66f65c1b4f15e1fabd938c3b1e9355f48)

**Comment by oliviermeslin** [comment]
Il me semble que le problème n'est pas entièrement résolu: `bpe_ens_2018` est toujours un `tibble`. Il faut peut-être refaire tourner le code, et recommitter les tables dans le dépôt?
