### ISSUE TITLE
telechargerDonnees : s'assurer de la présence des packages suggérés avant de télécharger

### ISSUE THREAD

**Issue by py-b** [pierre-lamarche/DoReMIFaSol#9]
J'ai essayé l'exemple de la doc : 
`bpe_ens_2018 <- telechargerDonnees(donnees = "BPE_ENS")`

Les données se sont téléchargées mais ça a planté car je n'avais pas readr.
`Error in loadNamespace(name) : there is no package called ‘readr’`

Donc le téléchargement s'est fait pour rien.

2 idées de solution : 
- vérifier la présence du package avant de lancer le téléchargement. Un truc du style : 
```
if (!requireNamepace("readr", quietly = TRUE)) {
  stop("nécessite le package `readr`")
}
```
- les mettre dans Imports plutôt que Suggests (sûrement too much si l'utilisateur ne veut pas utiliser la fonction téléchargement)

**Comment by pierre-lamarche** [comment]
Merci beaucoup @py-b , résolu [ici](https://github.com/pierre-lamarche/DoReMIFaSol/commit/9b82b237f2261f4e28a60e1484279d0213ab8b86)
